In [4]:
import numpy as np

In [4]:
#cria uma matriz unidimensional
mt = np.array([4,8,12,16,20,24])
print(mt)
print(type(mt))

[ 4  8 12 16 20 24]
<class 'numpy.ndarray'>


In [10]:
#cria um array com um tipo especifico
# array como float de 64 bits
mtfloat = np.array([1.5,2.0,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

#tipo inteiro 32 bits
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1.5 2.  3. ]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
#mudar o tipo de array
mtnewfloat = mt.astype(np.float64)
print(mtnewfloat)
print(type(mtnewfloat))

[ 4.  8. 12. 16. 20. 24.]
<class 'numpy.ndarray'>


In [16]:
#matriz bidimensional
mt1 = np.array([[1,2,3],[10,20,30],[100,200,300]])
print(mt1)
print(type(mt1))

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]
<class 'numpy.ndarray'>


In [26]:
#criar arrays vazios tipificados
#empty --> nao sao incializados, mas nao significa que sao vazios
#vai ter valores lixos nas posiçoes

vazio = np.empty([3,2], dtype = int)
print(vazio)
print("------")

#cria uma matriz 4x3 com valores 0
zeros = np.zeros([4,3], dtype = int)
print(zeros)
print("------")

#cria uma matriz 5x7 com valores 1
um = np.ones([5,7])
print(um)
print("------")

#croa matriz quadrada 5x5 com diagonal principal com valores 1 e os outros com valores 0
diag = np.eye(5)
print(diag)

[[         0 1073217536]
 [         0 1073741824]
 [         0 1074266112]]
------
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
#5 valores aleatorios entre 0 e 1
ale = np.random.random((5))
print(ale)
print("------------")

#5 valores aleatorios distribuiçao normal contendo negativos
aledistr = np.random.randn((5))
print(aledistr)
print("------------")

#matriz de valores aleatorios 3x4
#cada valor foi multiplicados por 10 para obter valores maiores
ale2 = (10*np.random.random((3,4)))
print(ale2)
print("------------")

[0.9561878  0.66689113 0.94399071 0.09564566 0.11340715]
------------
[ 0.06565216  1.34641149  0.1255515  -0.52241563  1.2735289 ]
------------
[[2.12349135 6.15379841 5.87788816 6.35437108]
 [3.51790455 2.27998161 5.53048252 5.78952845]
 [5.78084095 4.03031662 7.19674836 1.89481101]]
------------


In [50]:
#outra maneira de gerar valores aleatorios
#uso de SEMENTE ---> a semente é o valor 1
#sempre que repetir esse codigo, os numeros gerados serao os mesmos
gnr = np.random.default_rng(1)
ale3 = gnr.random(1)
print(ale3)
print("------------")

#gerar inteiros
# 10 ---> pode ser de 0 ate 10
#3,4 ---> matriz 3x4
ale4 = gnr.integers(10, size=(3,4))
print(ale4)
print("------------")

[0.51182162]
------------
[[7 9 0 1]
 [8 9 2 3]
 [8 4 2 8]]
------------


In [54]:
#unique remove repetições
j = np.array([10,11,12,13,10,11,12,13,20])
print(j)
print("---------")
j = np.unique(j)
print(j)

[10 11 12 13 10 11 12 13 20]
---------
[10 11 12 13 20]


In [60]:
#funções especificas
#cria a matriz bidimensional k
k = np.array([[17,18,19],[15,16,17], [12,13,14]])
print(k)
print("------------")
print(k[0][1])
print("------------")
#o tamanho das dimensoes da matriz
print(k.shape)

[[17 18 19]
 [15 16 17]
 [12 13 14]]
------------
18
------------
(3, 3)


In [66]:
#funçoes matematicas
print("Maior valor da matriz k: ", k.max())
print("Menor valor da matriz k: ", k.min())
print("Soma dos valores da matriz k: ", k.sum())
print("Media dos valores da matriz k: ", k.mean())
print("Desvio padrao dos valores da matriz k: ", k.std())

Maior valor da matriz k:  19
Menor valor da matriz k:  12
Soma dos valores da matriz k:  141
Media dos valores da matriz k:  15.666666666666666
Desvio padrao dos valores da matriz k:  2.211083193570267


In [70]:
#funções universais, aplicadas a todos os elementos
k1 = np.array([1,4,9,16,25,36])
print(k1)
print("Valor da raiz quadrada de cada elemento: ", np.sqrt(k1))
print("Valor exponencial de cada elemento: ", np.exp(k1))

[ 1  4  9 16 25 36]
Valor da raiz quadrada de cada elemento:  [1. 2. 3. 4. 5. 6.]
Valor exponencial de cada elemento:  [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [80]:
#extração de elementos
m = np.array([1,2,3,4,5,6])
print(m)
print(m[1])
print("------------")

#mostra o array criado a partir da posiçao 0, dois elementos, ignora o ultimo valor do intervalo [0,2[ aberto
print(m[0:2])
print("------------")

#mostra o array a partir da segunda posiçao (pos 1 ) ate o final
print(m[1:])
print("------------")

#mostra o array a partir da antepenultima posiçao ate o final
print(m[-3:])
print("------------")

[1 2 3 4 5 6]
2
------------
[1 2]
------------
[2 3 4 5 6]
------------
[4 5 6]
------------


In [88]:
#extração de linhas e colunas
l = np.array([[4,5], [6,7], [8,9]])
print(l)
print("------------")

l_linha1 = l[0, :]
print("Primeira linha, todas as colunas: ", l_linha1)
print("------------")

l_col1 = l[:, 0]
print("Primeira coluna, todas as linhas: ", l_col1)
print("------------")

l_col2 = l[:, 1]
print("Segunda coluna, todas as linhas: ", l_col2)
print("------------")

[[4 5]
 [6 7]
 [8 9]]
------------
Primeira linha, todas as colunas:  [4 5]
------------
Primeira coluna, todas as linhas:  [4 6 8]
------------
Segunda coluna, todas as linhas:  [5 7 9]
------------


In [96]:
#adiçao e multiplicaçao de matrizes
n = np.array([[1,2], [3,4]])
o = np.array([[1,1], [1,1]])
print(n)
print(o)
print("------------")

res1 = n+o
print("A soma das matrizes: \n" , res1)
print("------------")

res2 = n*o
print("A multiplicação das matrizes: \n", res2)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
------------
A soma das matrizes: 
 [[2 3]
 [4 5]]
------------
A multiplicação das matrizes: 
 [[1 2]
 [3 4]]


In [104]:
#adiçao e multiplicaçao em matrizes de dimensoes da linha diferentes
p = np.array([[1,2], [1,2]])
q = np.array([[1,1]])
print("Soma:\n" ,p+q)
print("Multiplição:\n", p*q)

Soma:
 [[2 3]
 [2 3]]
Multiplição:
 [[1 2]
 [1 2]]


In [8]:
#transposição
#rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
print(f)
print("------------")

#transposta a matriz f
print(f.T)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [10]:
#outro jeito de transpor
r = np.arange(15).reshape((3,5))
print(r)
print("------------")

s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [21]:
#expressoes logicas
#usando where
#cria matrizes com valores positivos e negativos

v = np.random.randn(4,4)
print(v)
print("------------")

#cria matriz com valores bool baseado no array v
#se v positivo, x ----> True, senao ---> False
x = (v>0)
print(x)
print("------------")

#cria matriz com valores -1 e 1 baseado nos valores do array x
#se x>0 ---> 1, senao ---> -1
z = np.where(x>0, 1, -1)
print(z)
print("------------")


[[-1.39697647  2.30154928 -1.63850064  0.54109819]
 [ 0.88263719 -1.47928334  1.14873675  0.00542434]
 [-1.0348336  -0.80994499  0.79296326 -0.86348541]
 [-0.14275502  0.33282487  1.11915049  0.53843326]]
------------
[[False  True False  True]
 [ True False  True  True]
 [False False  True False]
 [False  True  True  True]]
------------
[[-1  1 -1  1]
 [ 1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]]
------------
